[package]
name = "mobius"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive"] }
stderrlog = "0.6.0"
toml = "0.8.20"
log = "0.4.25"
