# .github/workflows/release.yml
on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  release-windows:
    name: release artifact for windows
    runs-on: windows-latest
    concurrency: 
      group: windows
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --profile release
      - name: run tests
        run: cargo test
      - name: compress artifact
        shell: pwsh
        run: Compress-Archive -Path .\target\release\mobius.exe -DestinationPath .\target\release\mobius-release-windows-x86_64.zip
      - name: release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobius-release-windows-x86_64
          path: .\target\release\mobius-release-windows-x86_64.zip
  release-linux-gnu:
    name: release artifact for linux
    runs-on: ubuntu-latest
    concurrency: 
      group: linux
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --profile release
      - name: run tests
        run: cargo test
      - name: compress artifact
        run: tar zcf ./target/release/mobius-release-linux-gnu.tgz ./target/release/mobius
      - name: release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobius-release-linux-x86_64
          path: ./target/release/mobius-release-linux-gnu.tgz