# .github/workflows/release.yml
on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  release:
    name: release artifact for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            executable: mobius.exe
            format: zip
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            executable: mobius
            format: tgz
    steps:
      - name: set rust version
        run: rustup override set stable
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --profile release
      - name: run tests
        run: cargo test
      - name: compress artifact
        uses: somaz94/compress-decompress@v1.5.1
        with:
          command: compress
          format: ${{ matrix.format }}
          source: ./target/release/${{ matrix.executable }}
          destfilename: mobius-release-${{ matrix.target }}.${{ matrix.format }}
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobius-release-${{ matrix.target }}
          path: ./target/release/mobius-release-${{ matrix.target }}.${{ matrix.format }}