# .github/workflows/release.yml
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and release artifact for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            compress_cmds: |
              Compress-Archive -Path .\target\release\mobius.exe -DestinationPath .\target\release\mobius-release-x86_64-pc-windows-gnu.zip
            archive: .\target\release\mobius-release-x86_64-pc-windows-gnu.zip
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            compress_cmds: |
              tar zcf ./target/release/mobius-release-x86_64-unknown-linux-gnu.tar.gz ./target/release/mobius
            archive: ./target/release/mobius-release-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - name: Set Rust version to stable
        run: rustup override set stable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build project
        run: cargo build --profile release
      - name: Run tests
        run: cargo test
      - name: Compress build artifact
        run: ${{ matrix.compress_cmds }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobius-release-${{ matrix.target }}
          path: ${{ matrix.archive }}
  release:
    name: Upload all artifacts to release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R ./artifacts
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.MOBIUS_RELEASE }}